---
title: Publications
---

## Publications

1. Mead TJ, Bhutada S, Peruzzi N, Adegboye J, **Seifert DE**, Cahill E, Drinko J, Donnellan E, Guggiliam A, Popovich Z, Griffin B, Tran-Lundmark K, Apte SS (2025) “ADAMTS7, a target in artherosclerosis, cooperates with its homolog ADAMTS12 to protect against myxomatous valve degeneration” *J Mol Cell Cardiol Plus*, 22:11:100288 doi: 10.1016/j.jmccpl.2025.100288

2.  Mead TJ, Bhutada S, Foulcer SJ, Peruzzi N, Nelson CM, **Seifert DE,** Larkin J, Tran-Lundmark K, Filmus J, Apte SS (2024) “Combined genetic-phamacologic inactivation of tightly linked ADAMTS proteases in temporally specific windows uncovers distinct roles for versican proteolysis and glypican-6 in cardiac development” *Matrix Biol*, 131:1-16, doi: 10.1016/j.matbio.2024.05.003

3.  Rypdal KB, Olav Melleby A, Robinson EL, Li J, Palmero S, **Seifert DE**, Martin D, Clark C, López B, Andreassen K, Dahl CP, Sjaastad I, Tønnessen T, Stokke MK, Louch WE, González A, Heymans S, Christensen G, Apte SS, Lunde IG (2022) “ADAMTSL3 knock-out mice develop cardiac dysfunction and dilatation with increased TGFb signalling after pressure overload” *Commun Biol,* 5(1):1392, doi:10.1038/s42003-022-04361-1

4.  Rypdal KB, Erusappan PM, Melleby AO, **Seifert DE**, Palmero S, Strand ME, Tonnessen T, Dahl CP, Almaas V, Hubmacher D, Apte SS, Christensen G, Lunde IG (2021) “The extracellular matrix glycoprotein ADAMTSL2 is increased in heart failure and inhibits TGFβ signaling in cardiac fibroblasts” *Sci Rep*, 11(1): 19757, doi: 10.1038/s41598-021-99032-2

5.  Martin DR, Witten JC, Tan CD, Rodrigues ER, Blackstone EH, Pettersson GB, **Seifert DE**, Willard BB, Apte SS (2020) “Proteomics identifies a convergent innate response to infective endocarditis and extensive proteolysis in vegetation components” *JCI Insight*, 5(14); e135317, doi: 10.1172/jci.insight.135317

## Presentations

1. **Seifert DE**, Alcocer AD, Rush EH, Lin C, Mead TJ (2024) “Improved Aortic Wall Structure and Longevity in Mouse Models of Marfan Syndrome with Conditional Inactivation of ADAMTS6” [Poster] Weinstein Cardiovascular Development and Regeneration Conference, 15-17 May, Montreal, Quebec; Poster 041

2. **Hoelting [Seifert] DE**, Apte SS (2018) “Gene targeting of ADAMSTL3, a novel participant in the musculoskeletal system” [Poster] American Society for Matrix Biology Biennial Meeting, 14-17 October, Las Vegas, Nevada; Poster B120	
