# This file controls the settings for your Quarto template from www.marvinschmitt.com

# website settings
website:
  title: "Deborah Seifert"                                # Your name
  description: "Extracellular Matrix Researcher"   # A brief slogan (optional)
  image: img/my_image.jpg
  
  favicon: img/favicon.png
  
  # start of the navigation bar at the top of the website
  navbar:
    pinned: true
    logo: /img/logo.png
    
    # your sub-pages
    left:
      - text: "Publications"
        href: publications/index.qmd
      - text: "CV"
        href: cv/index.qmd
      - text: "Blog"
        href: 
    
    # your social media handles
    right:
     - icon: linkedin
       href: https://www.linkedin.com/in/debbie-seifert-20ab461b6/
     - text: ORCID
       href: https://orcid.org/0000-0001-9247-1122 
     - icon: envelope
       href: "mailto:mail.dxs1072@case.edu"    
  
  

# Don't touch unless you know what you are doing :) ------------
  page-footer: 
    left: |
      <span class="faux-block">&#169; 2024 Deborah Seifert</span>
   
project:
  type: website
  output-dir: docs

  preview: 
    port: 22222
    browser: true
    watch-inputs: true
    navigate: true

execute:
  freeze: true

format:
  html:
    fontsize: 1.1em
    theme: 
      - sandstone
      - html/styles.scss
    toc: false
    code-link: true
    anchor-sections: true
    fig-cap-location: margin
    reference-location: margin
    footnotes-hover: true
